version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: moda_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moda_app
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: moda_redis
    ports:
      - '6379:6379'

volumes:
  mysql_data:
